import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavBar } from "@/components/navbar";
import { db, groups as groupsTable, groupUsers } from "@/db";
import { getSession } from "@/lib/sessions";
import { eq, getTableColumns } from "drizzle-orm";
import { redirect } from "next/navigation";

import "../globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();
    if (!session) redirect('/login');

    const groups = await db
        .select({ ...getTableColumns(groupsTable) })
        .from(groupUsers)
        .where(eq(groupUsers.user, session.userId))
        .leftJoin(groupsTable, eq(groupUsers.group, groupsTable.id));

    return (
        <>
            <NavBar groups={groups} currentGroup={session.groupId} />
            <main className="flex flex-col items-center">
                {children}
            </main>
        </>
    );
}
